# This is a workflow that emulates pushing to staging and production environments (hosted on Netlify)

name: Deploy App

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # This is a no-op job to pretend that we are running automated tests to simulate a full workflow
  automated-tests:
    name: Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
      - run: echo 'Running tests (placeholder)'
          
  deploy-staging:
    name: "Deploy to Staging"
    environment:
      name: Staging
    needs: [automated-tests]
    runs-on: ubuntu-latest
    # only run this workflow on main
    if: github.event.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: Build Astro site
        run: npm run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.STAGING_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
  deploy-production:
    name: "Deploy to Production"
    environment:
      name: Production
    needs: [automated-tests, deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: Build Astro site
        run: npm run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PRODUCTION_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
        
